### ISSUE TITLE
Is integration with Djoser gone in 0.3.x ? 

### ISSUE THREAD

**Issue by talolard** [merixstudio/django-trench#133]
Hi and thanks for the awesome and very helpful library. 
I'm trying to upgrade from trench 0.2.3 to 0.3.0 . I noticed that the djoser urls are gone. 
Is that forever or is there a workaround to get that working again ? 
Thanks

**Comment by trupus** [comment]
This would interest me as well

**Comment by allow-cookies** [comment]
Hi! Thank you for asking this question!

Apparently we forgot to mention this change in our `CHANGELOG.rst` file 😅 

Yes, we've decided to abandon the `djoser` integration for good as it was problematic for us due to unfrequent updates of the library. Sadly, there happened issues that weren't fixed for months.

Also, the latest release of the `djoser` library has taken place in October 2020, so we consider this library quite outdated and vulnerable (e.g. someone [reported](https://github.com/sunscrapers/djoser/issues/658) that timing attacks are possible).

We do not want to force our users to rely on a dependency that provides such an infrequent updates hence the decision of abandoning it 🙁.

After all you can integrate the `django-trench` library with `djoser` quite easily if you want to, really 😉
