### ISSUE TITLE
Problem with email 2FA method activation

### ISSUE THREAD

**Issue by tiln7** [merixstudio/django-trench#171]
I am experiencing problems with activating EMAIL 2FA method.

I am either getting back:
- "This field is required" - If I don't provide email field in the POST body
- "User with this email already exists" - If I provide email field in the POST body

**Anybody knows why? Email field isn't required according to the django-trench documentation.**

#settings.py
`
TRENCH_AUTH = {
    "MFA_METHODS": {
        "app": {
            "VERBOSE_NAME": "app",
            "VALIDITY_PERIOD": 30,
            "USES_THIRD_PARTY_CLIENT": True,
            "HANDLER": "trench.backends.application.ApplicationMessageDispatcher",
        },
        "email": {
            "VERBOSE_NAME": "email",
            "VALIDITY_PERIOD": 60 * 10,
            "HANDLER": "trench.backends.basic_mail.SendMailMessageDispatcher",
            "SOURCE_FIELD": "email",
            "EMAIL_SUBJECT": "Your MFA code",
            "EMAIL_PLAIN_TEMPLATE": "trench/backends/email/code.txt",
            "EMAIL_HTML_TEMPLATE": "trench/backends/email/code.html",
        },
    },
}
`

**User model:**
class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=100, null=True)

    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    organization = models.ForeignKey(
        "Organization", on_delete=models.CASCADE, null=True, blank=True, related_name="users"
    )
    settings = models.OneToOneField("UserSettings", on_delete=models.RESTRICT, null=True, blank=True)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["name"]

**If email field blank:**
<img width="1404" alt="Screenshot 2022-06-20 at 17 42 20" src="https://user-images.githubusercontent.com/39374789/174638562-d639c82b-a8c7-472b-bf65-ec0b10999654.png">
**If email field present:**
<img width="1388" alt="Screenshot at Jun 20 17-43-05" src="https://user-images.githubusercontent.com/39374789/174638581-a7a5f7ad-1f6b-46f8-8e2f-228e3e622291.png">

**Comment by Jeanluis019** [comment]
Same is happening to me.

Seems the problem is [here](https://github.com/merixstudio/django-trench/blob/6a9f3f049b6c1d97fbfd05e0527b693e04c33891/trench/views/base.py#L103), basically the serializer for this view is being generated on the fly and using the method name(email) as a required field.

Also, the serializer is using the `User` model, so when the serializer is called, it's really trying to create a new user with the email that you sent, and since the email is already being used by another user, it returns the error `user with this email already exists`.

**Comment by tiln7** [comment]
Hmm, how can we best resolve this?

**Comment by Jeanluis019** [comment]
Ok, I was reading and playing with the codebase more deeply and found the real cause of both errors:

**"This field is required":** in my `User` model, the email field can't be blank or null, and since this endpoint's serializer is a `ModelSerializer`, it's using the rules of the model.

**"User with this email already exists":** in my `User` model I set the `unique=True` attribute for the email field, so when I send the email in the request body, the serializer runs validations and raises an error because it sees that it exists a user with that email.

So, why the test for this endpoint ([test_add_user_mfa](https://github.com/merixstudio/django-trench/blob/e85b93eccedb41a15b2ff02b58ec56ee3686e766/testproject/tests/test_add_mfa.py#L17)) is not falling? Because this project is using the default `User` model of Django, and in that model, the [email field can be blank](https://github.com/django/django/blob/d80a2585532ef15184afed6cf4ec1358198a894d/django/contrib/auth/models.py#L358), that means, the email is not mandatory.

I'm thinking of the best way to fix this, I hope to create a PR soon.

**Comment by AndrewModus** [comment]
A potential workaround I used was to create a dummy 2fa email field email_2fa to add as a property to my custom user model. Eg in your `settings.py file` configure the mfa as such:

```python
TRENCH_AUTH = {
    ...
    "MFA_METHODS": {
        ...
        "email": {
            ...
            "SOURCE_FIELD": "email_2fa",
        }
    }
}
```


And then in your user model add the property
```python
class User(AbstractUser):
    ...
    @property
    def email_2fa(self):
        return self.email
```
