### ISSUE TITLE
OTP is not working for Google Authenticator app

### ISSUE THREAD

**Issue by SanjeevSundaravarathan** [merixstudio/django-trench#198]
Describe the bug
When activating MFA method the code generated by Google Authenticator, If the validity period is 300, then the code from iOS Google Authenticator app is working but not the one android app. If the validity period is 30, the code generated from both iOS and Android Google Authenticator app is not working.

I am receiving following response on the app/activate/confirm/ API endpoint when I use code from the Google Authenticator:
{"code":["Code invalid or expired."]}

To Reproduce

1. Create MFA method in Django Trench for app (Authenticator app) with validity 300 or 30
2. Generate and scan QR code or enter Account name and code manually using Google Authenticator.
3. Try to activate MFA method using code generated by app.
4. Check the response

Expected behavior
To be able to activate MFA method using Google Authenticator app.

**Comment by AleksaVu** [comment]
I have ran into the same problem when using Google Authenticator app. The problem was setting app VALIDITY_PERIOD to some value, and it was solved when completely removing that line of the setting. I assume the issue was mismatch between app's default code expiration time, and the expiration time from setting file.
