### ISSUE TITLE
Add lockout/throttling functionality to protect against brute force attacks

### ISSUE THREAD

**Issue by jamievleeshouwer** [merixstudio/django-trench#219]
It would be great if Django trench had the ability to either lockout a user for a specified period of time or throttle the user request rates in the views if a brute force attack is suspected.

This would benefit the: “first step” view as protecting against brute force password cracking is a fairly standard cyber security protection today.

It would also benefit the second step too. Given a code is typically 6 digits long it should take less that 1,000,000 (10^6) attempts to actually crack it (which isn’t that many if an attacker writes a piece of code).

**Comment by nefrob** [comment]
You can create your own [user rate throttles](https://www.django-rest-framework.org/api-guide/throttling/#userratethrottle) for MFA code verify/request and user name or ip address throttles for login. Then override the view to use the throttle classes.

I would assume this was left out since throttling behavior and needs vary by application. There are also many third party packages that extend DRF's base throttling classes making a default throttling setting redundant. 

Not too tricky to implement if desired though. Also it could be made configurable per view via trench settings so people can opt-in or pass their own throttle classes. You could give a crack at a PR or if there is agreement on adding this from the maintainers/community I'd be happy to put one together as well.

**Comment by jamievleeshouwer** [comment]
Thanks @nefrob, we have used inheritance as you suggested to throw in the throttle parameters (which is sufficiently simple)… You could probably also do it via monkey patching too…
